### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by Dalsie** [OhhLoz/Harvester#26]
This is a great module. I'm writing here simply to find out if it is being maintained?
Currently (19/12/2023), when installing the module through Forge, it does not appear to work at all. It creates several empty tables, and even when creating an actor an putting into the custom table, the module does not seem to function.

**Comment by OhhLoz** [comment]
Hi, it's no longer getting features but I am trying to maintain it for the newer Foundry versions. I've never tested it on Forge though, the empty compendiums is normally caused by an issue with migration from the v10 database format, sometimes foundry doesn't correctly migrate it. I can't say why the custom actor wouldn't work though.
If its possible on forge you can try using the v11 converted databases here:
https://github.com/OhhLoz/Harvester/issues/16
