### ISSUE TITLE
Unable to retrieve daggers from the bodies of enemies.

### ISSUE THREAD

**Issue by Akallabeth13666** [OhhLoz/Harvester#7]
Hi,

I am not sure if this is me doing something wrong or perhaps settings/modules I have but I seem to be unable to retrieve throwables from dead bodies.

![image](https://github.com/OhhLoz/Harvester/assets/95130435/8240d14e-3a98-4b54-9218-c2eb2d9d0c12)

It works fine when a separate pile is being created on hit (but it does not look nice when the loot icon covers the actual enemy).

I can see that the dagger was added to the inventory of the enemy, how do I retrieve it?

![image](https://github.com/OhhLoz/Harvester/assets/95130435/5ef83cbc-b218-41b3-8787-d369ce828cf1)

**Comment by OhhLoz** [comment]
Hi, the Loot action is only for currency, It doesn't transfer items at all. I didn't add the item transfer as other modules do this, hence why I added the option to completely disable the Loot action as the main focus of the module was on the Harvesting.
Harvesting does transfer items however its more of a universal X creature drops X rather than a case by case basis such as this

**Comment by Akallabeth13666** [comment]
Oh, ok, by the way, what other modules can transfer the items from the defeated NPC?

**Comment by OhhLoz** [comment]
The few I came across that matched the best when I was looking were:

- [Innocentis Loot](https://foundryvtt.com/packages/innocenti-loot)
- [DFreds Pocket Change](https://foundryvtt.com/packages/dfreds-pocket-change)

Some may work or work similarly like:

- [Items Piles (Not automatically I don't believe)](https://foundryvtt.com/packages/item-piles)
- [Simple Loot List](https://foundryvtt.com/packages/simple-loot-list)
- [Loot Sheet NPC 5e (Similar to Item Piles)](https://foundryvtt.com/packages/lootsheetnpc5e)

**Comment by Akallabeth13666** [comment]
Thanks
